language: c

os:
  - linux
  - osx

dist: focal
osx_image: xcode12.2

services:
- docker

jobs:
  include:
    - before_install:
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential curl; fi

    - script:
      - while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
      - SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build
      - kill %1
      name: native build

    - after_script:
      - ./build-ffmpeg --cleanup

    - script: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t ffmpeg:ubuntu -f Dockerfile .; fi
      name: build in docker

    - script: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t ffmpeg:ubuntu -f Dockerfile .; fi
      name: build in docker with cuda
