language: shell

os: linux
dist: focal

jobs:
  include:
    - name: native build in linux
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq build-essential curl ca-certificates libz-dev
      script:
        - while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build
        - kill %1
      after_script:
        - ./build-ffmpeg --cleanup

    - name: native build in osx
      os: osx
      osx_image: xcode12.2
      script:
        - while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build
        - kill %1
      after_script:
        - ./build-ffmpeg --cleanup

    - name: build in docker
      script:
        - docker build -t ffmpeg:ubuntu -f Dockerfile .
      after_script:
        - docker run --rm ffmpeg:ubuntu

    - name: build in docker with cuda
      script:
        - docker build -t ffmpeg:cuda -f cuda-ubuntu.dockerfile .
      after_script:
        - docker run --rm ffmpeg:cuda