language: c

services:
  - docker

job:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12.2

job:
  include:
    - name: native build
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential curl; fi

      script:
        - while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build
        - kill %1

      after_script:
        - ./build-ffmpeg --cleanup

  exclude:
    - name: build in docker
      os: osx
      before_install:
        - docker build -t ffmpeg:ubuntu -f Dockerfile .
      script:
        - docker run --rm ffmpeg:ubuntu

    - name: build in docker with cuda
      os: osx
      before_install:
        - docker build -t ffmpeg:cuda -f cuda-ubuntu.dockerfile .
      script:
        - docker run --rm ffmpeg:cuda
