language: minimal

dist: focal
osx_image: xcode12.2

services: docker

jobs:
  include:
    - name: native build
      os:
      - linux
      - osx
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential curl; fi

      script:
        - while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build
        - kill %1

      after_script:
        - ./build-ffmpeg --cleanup

    - name: build in docker
      os: linux
      script: docker build -t ffmpeg:ubuntu -f Dockerfile .

    - name: build in docker with cuda
      os: linux
      script: docker build -t ffmpeg:cuda -f cuda-ubuntu.dockerfile .
