name: Docker build

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  MAIN_PLATFORM: debian

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f Dockerfile .
